apiVersion: v1
kind: Secret
metadata:
  name: cd2024bfs2g1-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"  
data:
  password: {{  "cd2024bfs2g1"  | b64enc }}
  user: {{ "postgres" | b64enc }}
  postgresql-password: {{  "cd2024bfs2g1"  | b64enc }}
